# TODO: IMPORT GOOGLE API

# TODO: CREATE FUNCTIONS TO GET TRANSLATION TEXT --> SOURCE.TXT , TARGET.TXT

# TODO: CREATE FUNCTION TO SEND SOURCE TEXT TO GOOGLE API

# TODO: CREATE FUNCTION TO FORMAT RETURNED JSON